from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name='Customer',
			fields=[
				('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
				('first_name', models.TextField()),
				('last_name', models.TextField()),
				('email', models.TextField()),
				('phone', models.TextField(blank=True, null=True)),
				('company', models.TextField(blank=True, null=True)),
				('address', models.TextField(blank=True, null=True)),
				('status', models.TextField(default='prospect')),
				('priority', models.TextField(default='medium')),
				('lead_source', models.TextField(blank=True, null=True)),
				('notes', models.TextField(blank=True, null=True)),
				('survey_type', models.CharField(blank=True, max_length=100, null=True)),
				('location', models.TextField(blank=True, null=True)),
				('property_details', models.JSONField(blank=True, null=True)),
				('service_category', models.CharField(blank=True, max_length=100, null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('last_contact', models.DateTimeField(blank=True, null=True)),
			],
			options={'db_table': 'customers'},
		),
		migrations.CreateModel(
			name='Project',
			fields=[
				('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
				('name', models.TextField()),
				('description', models.TextField(blank=True, null=True)),
				('status', models.TextField(default='planning')),
				('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
				('start_date', models.DateTimeField(blank=True, null=True)),
				('end_date', models.DateTimeField(blank=True, null=True)),
				('survey_type', models.CharField(blank=True, max_length=100, null=True)),
				('location', models.TextField(blank=True, null=True)),
				('area', models.CharField(blank=True, max_length=100, null=True)),
				('plot_number', models.CharField(blank=True, max_length=100, null=True)),
				('survey_number', models.CharField(blank=True, max_length=100, null=True)),
				('village', models.CharField(blank=True, max_length=255, null=True)),
				('district', models.CharField(blank=True, max_length=255, null=True)),
				('state', models.CharField(blank=True, max_length=100, null=True)),
				('coordinates', models.JSONField(blank=True, null=True)),
				('equipment_used', models.TextField(blank=True, null=True)),
				('team_members', models.JSONField(blank=True, null=True)),
				('deliverables', models.JSONField(blank=True, null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.customer')),
			],
			options={'db_table': 'projects'},
		),
		migrations.CreateModel(
			name='SurveyRecord',
			fields=[
				('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
				('survey_type', models.CharField(max_length=100)),
				('survey_number', models.CharField(blank=True, max_length=100, null=True)),
				('plot_number', models.CharField(blank=True, max_length=100, null=True)),
				('area', models.CharField(blank=True, max_length=100, null=True)),
				('location', models.TextField(blank=True, null=True)),
				('village', models.CharField(blank=True, max_length=255, null=True)),
				('district', models.CharField(blank=True, max_length=255, null=True)),
				('state', models.CharField(default='Tamil Nadu', max_length=100)),
				('coordinates', models.JSONField(blank=True, null=True)),
				('boundaries', models.JSONField(blank=True, null=True)),
				('measurements', models.JSONField(blank=True, null=True)),
				('notes', models.TextField(blank=True, null=True)),
				('status', models.TextField(default='in_progress')),
				('survey_date', models.DateTimeField(blank=True, null=True)),
				('completed_date', models.DateTimeField(blank=True, null=True)),
				('surveyor_name', models.CharField(blank=True, max_length=255, null=True)),
				('equipment_used', models.TextField(blank=True, null=True)),
				('accuracy', models.CharField(blank=True, max_length=50, null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_records', to='core.customer')),
				('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_records', to='core.project')),
			],
			options={'db_table': 'survey_records'},
		),
		migrations.CreateModel(
			name='Lead',
			fields=[
				('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
				('stage', models.TextField(default='prospecting')),
				('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
				('probability', models.IntegerField(default=0)),
				('expected_close_date', models.DateTimeField(blank=True, null=True)),
				('notes', models.TextField(blank=True, null=True)),
				('service_type', models.CharField(blank=True, max_length=100, null=True)),
				('inquiry_source', models.CharField(blank=True, max_length=100, null=True)),
				('urgency', models.CharField(default='medium', max_length=20)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.customer')),
			],
			options={'db_table': 'leads'},
		),
		migrations.CreateModel(
			name='Communication',
			fields=[
				('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
				('type', models.TextField()),
				('subject', models.TextField(blank=True, null=True)),
				('content', models.TextField()),
				('direction', models.TextField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='core.customer')),
			],
			options={'db_table': 'communications'},
		),
		migrations.CreateModel(
			name='AdminUser',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=100)),
				('email', models.CharField(max_length=100)),
				('password', models.CharField(max_length=100)),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
			options={'db_table': 'admin'},
		),
		migrations.CreateModel(
			name='ClientRegister',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('user_name', models.CharField(max_length=255)),
				('password', models.CharField(max_length=255)),
				('phone_number', models.CharField(max_length=15)),
				('email', models.CharField(max_length=255)),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
			options={'db_table': 'client_register'},
		),
		migrations.CreateModel(
			name='LdrContact',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=255)),
				('email', models.CharField(max_length=255)),
				('phone_number', models.CharField(max_length=255)),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
			options={'db_table': 'ldr_contact'},
		),
		migrations.CreateModel(
			name='LdrCareer',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=255)),
				('email', models.CharField(max_length=255)),
				('phone_number', models.CharField(max_length=255)),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
			options={'db_table': 'ldr_career'},
		),
	]
