from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

	dependencies = [
		('core', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='OtpVerification',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('email', models.CharField(max_length=255)),
				('otp', models.CharField(max_length=6)),
				('expires_at', models.DateTimeField()),
				('is_used', models.BooleanField(default=False)),
				('purpose', models.CharField(default='signup', max_length=50)),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
			options={'db_table': 'otp_verifications'},
		),
		migrations.CreateModel(
			name='PendingUser',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('username', models.CharField(max_length=50)),
				('email', models.CharField(max_length=255)),
				('password_hash', models.CharField(max_length=255)),
				('role', models.CharField(default='user', max_length=20)),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
			options={'db_table': 'pending_users'},
		),
		migrations.CreateModel(
			name='UserCustomerData',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=255)),
				('email', models.CharField(max_length=255)),
				('phone', models.CharField(blank=True, max_length=20, null=True)),
				('company', models.CharField(blank=True, max_length=255, null=True)),
				('address', models.TextField(blank=True, null=True)),
				('notes', models.TextField(blank=True, null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_data', to=settings.AUTH_USER_MODEL)),
			],
			options={'db_table': 'user_customer_data'},
		),
		migrations.CreateModel(
			name='FeatureRequest',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('title', models.TextField()),
				('description', models.TextField()),
				('category', models.TextField()),
				('priority', models.TextField(default='Medium')),
				('status', models.TextField(default='Submitted')),
				('submittedBy', models.TextField()),
				('assignedTo', models.TextField(blank=True, null=True)),
				('estimatedHours', models.IntegerField(blank=True, null=True)),
				('actualHours', models.IntegerField(blank=True, null=True)),
				('businessValue', models.TextField(blank=True, null=True)),
				('technicalNotes', models.TextField(blank=True, null=True)),
				('userRole', models.TextField()),
				('createdAt', models.DateTimeField(auto_now_add=True)),
				('updatedAt', models.DateTimeField(auto_now=True)),
				('completedAt', models.DateTimeField(blank=True, null=True)),
			],
			options={'db_table': 'feature_requests'},
		),
		migrations.CreateModel(
			name='AuditLog',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('userId', models.TextField()),
				('userName', models.TextField()),
				('userRole', models.TextField()),
				('action', models.TextField()),
				('tableName', models.TextField()),
				('recordId', models.TextField(blank=True, null=True)),
				('oldValues', models.TextField(blank=True, null=True)),
				('newValues', models.TextField(blank=True, null=True)),
				('ipAddress', models.TextField(blank=True, null=True)),
				('userAgent', models.TextField(blank=True, null=True)),
				('sessionId', models.TextField(blank=True, null=True)),
				('timestamp', models.DateTimeField(auto_now_add=True)),
			],
			options={'db_table': 'audit_logs'},
		),
		migrations.CreateModel(
			name='Notification',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('userId', models.TextField()),
				('userRole', models.TextField()),
				('type', models.TextField()),
				('title', models.TextField()),
				('message', models.TextField()),
				('relatedTable', models.TextField(blank=True, null=True)),
				('relatedId', models.TextField(blank=True, null=True)),
				('isRead', models.BooleanField(default=False)),
				('priority', models.TextField(default='normal')),
				('createdAt', models.DateTimeField(auto_now_add=True)),
				('readAt', models.DateTimeField(blank=True, null=True)),
			],
			options={'db_table': 'notifications'},
		),
		migrations.CreateModel(
			name='UserLeave',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('leaveType', models.CharField(max_length=50)),
				('startDate', models.DateTimeField()),
				('endDate', models.DateTimeField()),
				('totalDays', models.IntegerField()),
				('reason', models.TextField()),
				('status', models.CharField(default='pending', max_length=20)),
				('appliedAt', models.DateTimeField(auto_now_add=True)),
				('approvedAt', models.DateTimeField(blank=True, null=True)),
				('rejectedReason', models.TextField(blank=True, null=True)),
				('createdAt', models.DateTimeField(auto_now_add=True)),
				('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
			],
			options={'db_table': 'user_leaves'},
		),
		migrations.CreateModel(
			name='Holiday',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=255)),
				('date', models.DateTimeField()),
				('description', models.TextField(blank=True, null=True)),
				('type', models.CharField(default='public', max_length=50)),
				('isActive', models.BooleanField(default=True)),
				('createdAt', models.DateTimeField(auto_now_add=True)),
			],
			options={'db_table': 'holidays'},
		),
		migrations.CreateModel(
			name='AppUser',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('username', models.CharField(max_length=50, unique=True)),
				('email', models.CharField(max_length=255, unique=True)),
				('password_hash', models.CharField(max_length=255)),
				('role', models.CharField(default='user', max_length=20)),
				('phone_number', models.CharField(blank=True, max_length=20, null=True)),
				('company', models.CharField(blank=True, max_length=255, null=True)),
				('first_name', models.CharField(blank=True, max_length=100, null=True)),
				('last_name', models.CharField(blank=True, max_length=100, null=True)),
				('is_active', models.BooleanField(default=True)),
				('is_verified', models.BooleanField(default=False)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('last_login', models.DateTimeField(blank=True, null=True)),
			],
			options={'db_table': 'users'},
		),
	]
